version: '3.8'

services:
  frontend:
    container_name: cosmic-defenders-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - game-network

networks:
  game-network:
    external: true