version: '3.8'

services:
  # Frontend service
    # Frontend service
  frontend:
    container_name: cosmic-defenders-frontend
    image: cosmic_defenders_web-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      - API_URL=http://game-api:8000  # Backend URL'yi ekleyin
    networks:
      - game-network
    depends_on:
      - game-api

  # Game API service
  game-api:
    container_name: game-api-container
    build:
      context: .  # Dockerfile'ınızın bulunduğu dizin
      dockerfile: Dockerfile  # Dockerfile'ı belirtiyoruz
    environment:
      - ORACLE_USER=C##COSMIC_DEFENDERS
      - ORACLE_PASSWORD=MyPassword123
      - ORACLE_HOST=oracle-db  # Burada oracle-db'nin mevcut konteyneri kullanılacak
      - ORACLE_PORT=1521
      - ORACLE_SID=XE
      - SECRET_KEY=48cf0472d3f2d96f4aa35850d325e0ee091b68a5c9cb970e3b696020d9da431b
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"  # FastAPI için port yönlendirme
    networks:
      - game-network

 

networks:
  game-network:
    driver: bridge

volumes:
  oradata:
